# Workflow derived from https://github.com/posit-dev/setup-air/tree/main/examples

on:
  push:
    branches: [main, master]
  pull_request:

name: format-check.yaml

permissions: read-all

jobs:
  format-check:
    runs-on: codeberg-tiny
    steps:
      - uses: https://github.com/actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install air
        run: curl -fsSL https://github.com/posit-dev/air/releases/latest/download/air-installer.sh | sh

      - name: Check
        run: air format . --check
